# Generated by Django 2.2.6 on 2019-11-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191031_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_annotation',
            field=models.CharField(max_length=1000, verbose_name='Аннотация статьи'),
        ),
    ]
